//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityQuestions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Program {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Program() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecurityQuestions.Resources.Program", typeof(Program).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to answer a security question?.
        /// </summary>
        internal static string ANSWER_QUESTIONS {
            get {
                return ResourceManager.GetString("ANSWER_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, Please enter your name or &apos;quit&apos; to exit?.
        /// </summary>
        internal static string ASK_NAME {
            get {
                return ResourceManager.GetString("ASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your response matchs, congratulations..
        /// </summary>
        internal static string CORRECT_RESPONSE {
            get {
                return ResourceManager.GetString("CORRECT_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer the below question or press [enter] to skip..
        /// </summary>
        internal static string ENTER_ANSWER {
            get {
                return ResourceManager.GetString("ENTER_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the correct response for this security question..
        /// </summary>
        internal static string ENTER_RESPONSE {
            get {
                return ResourceManager.GetString("ENTER_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter (y/n):.
        /// </summary>
        internal static string ENTER_Y_OR_N {
            get {
                return ResourceManager.GetString("ENTER_Y_OR_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .
        /// </summary>
        internal static string GREETING {
            get {
                return ResourceManager.GetString("GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your response didn&apos;t match, sorry..
        /// </summary>
        internal static string INCORRECT_RESPONSE {
            get {
                return ResourceManager.GetString("INCORRECT_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 2 character, please try again..
        /// </summary>
        internal static string MIN_2_CHARACTERS {
            get {
                return ResourceManager.GetString("MIN_2_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That was the last question. Please try again later..
        /// </summary>
        internal static string OUT_OF_QUESTIONS {
            get {
                return ResourceManager.GetString("OUT_OF_QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping this question.
        /// </summary>
        internal static string SKIP_QUESTION {
            get {
                return ResourceManager.GetString("SKIP_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to store answers to security questions?.
        /// </summary>
        internal static string STORE_ANSWERS {
            get {
                return ResourceManager.GetString("STORE_ANSWERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a nice day!.
        /// </summary>
        internal static string THE_END {
            get {
                return ResourceManager.GetString("THE_END", resourceCulture);
            }
        }
    }
}
